ERROR - 2023-02-09 00:51:30 --> mysqli_sql_exception: Unknown column 'nama_lengkap' in 'OLD' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
CRITICAL - 2023-02-09 00:51:30 --> Unknown column 'nama_lengkap' in 'OLD'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER `log_delete_user` BEFORE UPDATE ON `user` FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (Old.id_user, old.nama_lengkap, old.email,NOW(),"Hapus data user");
        END', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER `log_delete_user` BEFORE UPDATE ON `user` FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (Old.id_user, old.nama_lengkap, old.email,NOW(),"Hapus data user");
        END')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER `log_delete_user` BEFORE UPDATE ON `user` FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (Old.id_user, old.nama_lengkap, old.email,NOW(),"Hapus data user");
        END')
 4 APPPATH\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER `log_delete_user` BEFORE UPDATE ON `user` FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (Old.id_user, old.nama_lengkap, old.email,NOW(),"Hapus data user");
        END')
 5 APPPATH\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 00:53:15 --> mysqli_sql_exception: Trigger 'cor4.trigger_hapus_buku' already exists in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(87): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(107): App\Models\SemuaTriggerModel->trigger_hapus_buku()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_hapus_buku()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
CRITICAL - 2023-02-09 00:53:15 --> Trigger 'cor4.trigger_hapus_buku' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER `trigger_hapus_buku` AFTER DELETE ON `hlmnbuku` FOR EACH 
        ROW BEGIN
        INSERT INTO log_buku (keterangan, waktu, id_buku, judulbuku)
        VALUES("Menghapus buku", NOW(), OLD.id_buku, OLD.judulbuku);
        END', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER `trigger_hapus_buku` AFTER DELETE ON `hlmnbuku` FOR EACH 
        ROW BEGIN
        INSERT INTO log_buku (keterangan, waktu, id_buku, judulbuku)
        VALUES("Menghapus buku", NOW(), OLD.id_buku, OLD.judulbuku);
        END')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER `trigger_hapus_buku` AFTER DELETE ON `hlmnbuku` FOR EACH 
        ROW BEGIN
        INSERT INTO log_buku (keterangan, waktu, id_buku, judulbuku)
        VALUES("Menghapus buku", NOW(), OLD.id_buku, OLD.judulbuku);
        END')
 4 APPPATH\Models\SemuaTriggerModel.php(87): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER `trigger_hapus_buku` AFTER DELETE ON `hlmnbuku` FOR EACH 
        ROW BEGIN
        INSERT INTO log_buku (keterangan, waktu, id_buku, judulbuku)
        VALUES("Menghapus buku", NOW(), OLD.id_buku, OLD.judulbuku);
        END')
 5 APPPATH\Controllers\SemuaTrigger.php(107): App\Models\SemuaTriggerModel->trigger_hapus_buku()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_hapus_buku()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 00:53:34 --> mysqli_sql_exception: Trigger 'cor4.trigger_hapus_buku' already exists in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(87): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(107): App\Models\SemuaTriggerModel->trigger_hapus_buku()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_hapus_buku()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
ERROR - 2023-02-09 00:53:37 --> mysqli_sql_exception: Trigger 'cor4.trigger_penambahan_buku' already exists in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(96): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(124): App\Models\SemuaTriggerModel->trigger_penambahan_buku()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_penambahan_buku()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
ERROR - 2023-02-09 00:53:41 --> mysqli_sql_exception: Trigger 'cor4.trigger_perubahan_buku' already exists in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(105): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(141): App\Models\SemuaTriggerModel->trigger_perubahan_buku()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_perubahan_buku()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
ERROR - 2023-02-09 00:54:02 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
ERROR - 2023-02-09 00:54:22 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 00:54:22 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$H/rxzEsfhwqCVq/RVdbEXuYo4ft0rjmDw09hSWrfwvRTkEQtig/ca\', \'2023-02-09 13:54:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$H/rxzEsfhwqCVq/RVdbEXuYo4ft0rjmDw09hSWrfwvRTkEQtig/ca\', \'2023-02-09 13:54:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$H/rxzEsfhwqCVq/RVdbEXuYo4ft0rjmDw09hSWrfwvRTkEQtig/ca\', \'2023-02-09 13:54:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (:email:, :username:, :nama_user:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 00:54:41 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 00:54:41 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$klU2abI0RCeZeyAJgGCB/O3KRNBWMXa6iE/01nISPngo83izOJS6G\', \'2023-02-09 13:54:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$klU2abI0RCeZeyAJgGCB/O3KRNBWMXa6iE/01nISPngo83izOJS6G\', \'2023-02-09 13:54:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'Haruman wiguna\', \'$2y$10$klU2abI0RCeZeyAJgGCB/O3KRNBWMXa6iE/01nISPngo83izOJS6G\', \'2023-02-09 13:54:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (:email:, :username:, :nama_user:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 00:56:31 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 00:56:31 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NMB9IyqExPp55jCWBD/LsO1RhDWfCvnM3jl98NZIgFRtnMiqZyrBe\', \'2023-02-09 13:56:31\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NMB9IyqExPp55jCWBD/LsO1RhDWfCvnM3jl98NZIgFRtnMiqZyrBe\', \'2023-02-09 13:56:31\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NMB9IyqExPp55jCWBD/LsO1RhDWfCvnM3jl98NZIgFRtnMiqZyrBe\', \'2023-02-09 13:56:31\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (:email:, :username:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 00:56:49 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 00:56:49 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$XXpytaRIrVOhDfncbip/F.gYuZq3d737RjA.hZa7a.FxMdugVq7qG\', \'2023-02-09 13:56:49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$XXpytaRIrVOhDfncbip/F.gYuZq3d737RjA.hZa7a.FxMdugVq7qG\', \'2023-02-09 13:56:49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$XXpytaRIrVOhDfncbip/F.gYuZq3d737RjA.hZa7a.FxMdugVq7qG\', \'2023-02-09 13:56:49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`email`, `username`, `password`, `date_created`) VALUES (:email:, :username:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:00:02 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `Us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 01:00:02 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `User` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NohrvF2J8ZLce0UHSptrP.5fL8B2qDAju01cgPkLDuRvpLTbImBce\', \'2023-02-09 14:00:02\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `User` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NohrvF2J8ZLce0UHSptrP.5fL8B2qDAju01cgPkLDuRvpLTbImBce\', \'2023-02-09 14:00:02\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `User` (`email`, `username`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'$2y$10$NohrvF2J8ZLce0UHSptrP.5fL8B2qDAju01cgPkLDuRvpLTbImBce\', \'2023-02-09 14:00:02\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `User` (`email`, `username`, `password`, `date_created`) VALUES (:email:, :username:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:01:06 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `Us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 01:01:06 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `User` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'AAAA\', \'$2y$10$GRVxgnDPda/qrHmWn3sdPOOkw0M3VXkh6xfF9ylBokjQGG0P3nDoO\', \'2023-02-09 14:01:06\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `User` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'AAAA\', \'$2y$10$GRVxgnDPda/qrHmWn3sdPOOkw0M3VXkh6xfF9ylBokjQGG0P3nDoO\', \'2023-02-09 14:01:06\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `User` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (\'iqbalardimansyah@upi.edu\', \'asepjajang\', \'AAAA\', \'$2y$10$GRVxgnDPda/qrHmWn3sdPOOkw0M3VXkh6xfF9ylBokjQGG0P3nDoO\', \'2023-02-09 14:01:06\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `User` (`email`, `username`, `nama_user`, `password`, `date_created`) VALUES (:email:, :username:, :nama_user:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(130): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:03:21 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `Us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(129): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 01:03:21 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `User` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$BuvsZz88pCc/i4EsNYTkAuN5AwR6yQDgxsY2Dbl9Mlut7GG/avvnS\', \'2023-02-09 14:03:21\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `User` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$BuvsZz88pCc/i4EsNYTkAuN5AwR6yQDgxsY2Dbl9Mlut7GG/avvnS\', \'2023-02-09 14:03:21\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `User` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$BuvsZz88pCc/i4EsNYTkAuN5AwR6yQDgxsY2Dbl9Mlut7GG/avvnS\', \'2023-02-09 14:03:21\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `User` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (:nama_user:, :username:, :email:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(129): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:05:35 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(129): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 01:05:35 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$uH43qTif/Rl0aCuO13KSeO5loJyTiytgv06waWw8aOtdTD.LbFNd6\', \'2023-02-09 14:05:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$uH43qTif/Rl0aCuO13KSeO5loJyTiytgv06waWw8aOtdTD.LbFNd6\', \'2023-02-09 14:05:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$uH43qTif/Rl0aCuO13KSeO5loJyTiytgv06waWw8aOtdTD.LbFNd6\', \'2023-02-09 14:05:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `date_created`) VALUES (:nama_user:, :username:, :email:, :password:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(129): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:07:43 --> mysqli_sql_exception: Unknown column 'nama_user' in 'field list' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\CI4\CI4-LIB-PushCI4\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\CI4\CI4-LIB-PushCI4\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\CI4\CI4-LIB-PushCI4\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Auth.php(131): CodeIgniter\BaseModel->save(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Auth->save()
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#14 {main}
CRITICAL - 2023-02-09 01:07:43 --> Unknown column 'nama_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `role`, `is_active`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$ZMjuEubryPlFU0DGw5Pr3OrZKe8nRimk4Ldk0EHkeiX7lB9BALTa.\', 2, 1, \'2023-02-09 14:07:43\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `role`, `is_active`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$ZMjuEubryPlFU0DGw5Pr3OrZKe8nRimk4Ldk0EHkeiX7lB9BALTa.\', 2, 1, \'2023-02-09 14:07:43\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `role`, `is_active`, `date_created`) VALUES (\'AAAA\', \'asepjajang\', \'iqbalardimansyah@upi.edu\', \'$2y$10$ZMjuEubryPlFU0DGw5Pr3OrZKe8nRimk4Ldk0EHkeiX7lB9BALTa.\', 2, 1, \'2023-02-09 14:07:43\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`nama_user`, `username`, `email`, `password`, `role`, `is_active`, `date_created`) VALUES (:nama_user:, :username:, :email:, :password:, :role:, :is_active:, :date_created:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(131): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:18:44 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cor4' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'cor4', 3306, '', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#5 D:\CI4\CI4-LIB-PushCI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 D:\CI4\CI4-LIB-PushCI4\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 D:\CI4\CI4-LIB-PushCI4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\CI4\CI4-LIB-PushCI4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\CI4\CI4-LIB-PushCI4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\CI4\CI4-LIB-PushCI4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\CI4\CI4-LIB-PushCI4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cor4' in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(1360): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(1394): CodeIgniter\Database\BaseConnection->listTables()
#4 D:\CI4\CI4-LIB-PushCI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 D:\CI4\CI4-LIB-PushCI4\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 D:\CI4\CI4-LIB-PushCI4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 D:\CI4\CI4-LIB-PushCI4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 D:\CI4\CI4-LIB-PushCI4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 D:\CI4\CI4-LIB-PushCI4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#11 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 D:\CI4\CI4-LIB-PushCI4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#14 D:\CI4\CI4-LIB-PushCI4\spark(98): CodeIgniter\CLI\Console->run()
#15 {main}
CRITICAL - 2023-02-09 01:22:15 --> Undefined array key "nama_anda"
in APPPATH\Controllers\Auth.php on line 222.
 1 APPPATH\Controllers\Auth.php(222): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nama_anda"', 'APPPATH\\Controllers\\Auth.php', 222)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->loginSave()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-09 01:23:00 --> Undefined array key "nama_anda"
in APPPATH\Controllers\Auth.php on line 222.
 1 APPPATH\Controllers\Auth.php(222): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "nama_anda"', 'APPPATH\\Controllers\\Auth.php', 222)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->loginSave()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:23:14 --> mysqli_sql_exception: Table 'cor4.trendingbook' doesn't exist in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT * FROM t...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM t...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM t...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Views\home\index.php(42): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#4 D:\CI4\CI4-LIB-PushCI4\system\View\View.php(213): include('D:\\CI4\\CI4-LIB-...')
#5 D:\CI4\CI4-LIB-PushCI4\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 D:\CI4\CI4-LIB-PushCI4\system\Common.php(1134): CodeIgniter\View\View->render('home/index', Array, true)
#7 D:\CI4\CI4-LIB-PushCI4\app\Controllers\Home.php(27): view('home/index', Array)
#8 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\Home->index()
#9 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#13 {main}
CRITICAL - 2023-02-09 01:23:14 --> Table 'cor4.trendingbook' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT * FROM trendingbook', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM trendingbook')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM trendingbook')
 4 APPPATH\Views\home\index.php(42): CodeIgniter\Database\BaseConnection->query('SELECT * FROM trendingbook')
 5 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\home\\index.php')
 6 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 7 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('home/index', [], true)
 8 APPPATH\Controllers\Home.php(27): view('home/index', [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Home->index()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2023-02-09 01:26:12 --> mysqli_sql_exception: Trigger 'cor4.log_update_user' already exists in D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\CI4\CI4-LIB-PushCI4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\CI4\CI4-LIB-PushCI4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\CI4\CI4-LIB-PushCI4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\CI4\CI4-LIB-PushCI4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\CI4\CI4-LIB-PushCI4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\CI4\CI4-LIB-PushCI4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\CI4\CI4-LIB-PushCI4\system\Commands\Server\rewrite.php(46): require_once('D:\\CI4\\CI4-LIB-...')
#10 {main}
CRITICAL - 2023-02-09 01:26:12 --> Trigger 'cor4.log_update_user' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER log_update_user AFTER UPDATE ON user FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (NEW.id_user, NEW.nama_user, NEW.email, NOW(), "update data user baru");
        END', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER log_update_user AFTER UPDATE ON user FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (NEW.id_user, NEW.nama_user, NEW.email, NOW(), "update data user baru");
        END')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER log_update_user AFTER UPDATE ON user FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (NEW.id_user, NEW.nama_user, NEW.email, NOW(), "update data user baru");
        END')
 4 APPPATH\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER log_update_user AFTER UPDATE ON user FOR EACH ROW begin
        INSERT INTO log_user(id_user,nama_user,email_user,waktu_terdaftar,keterangan)
        VALUES (NEW.id_user, NEW.nama_user, NEW.email, NOW(), "update data user baru");
        END')
 5 APPPATH\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
